on:
  push:
    tags:
      - concordium-news-webhooks/*

jobs:
  release-concordium-news-webhooks-image:
    uses: concordium/.github/.github/workflows/docker-release-workflow.yaml@v1
    with:
      SERVICE_NAME: "concordium-news-webhooks"
      BUILD_ARGS: |
        build_image=python:3.8-slim
      DOCKER_FILE_PATH: Dockerfile
    secrets: inherit
    
